name: Deploy TigerTix Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      #Deploy authentication service
      - name: Deploy Authentication Service
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_AUTHENTICATION_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      #Deploy client service
      - name: Deploy Client Service
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_CLIENT_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      #Deploy Admin service
      - name: Deploy Admin Service
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_ADMIN_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      #Deploy LLM service
      - name: Deploy LLM Service
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_LLM_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"

      # Deploy backend
      - name: Deploy Backend Service
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_BACKEND_KEY }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
